version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
  frontend:
    build: "./frontend"
    env_file:
      - .env.public
      - .env.local
    ports:
      - 3000:3000
  server:
    build: "./server"
    env_file:
      - .env.public
      - .env.local
    ports:
      - 3030:3030
volumes:
  mongo:
